import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  // let formvalue = "";

  // let decimals = 114514;
  let hexagon = 6;

  // let decimals_to_string = decimals.toString();
  // let decimals_to_hexagon = decimals.toString(hexagon);
  // let hexagon_to_eridians = decimals_to_hexagon.replaceAll("0","ℓ").replaceAll("1","I").replaceAll("2","V").replaceAll("3","λ").replaceAll("4","＋").replaceAll("5","∀");

  let eridian_numbers = ""

  const [dec, setDec] = React.useState(0)
  const [hex, setHex] = React.useState(0)
  const [eri, setEri] = React.useState("ℓ")

  const handleSubmit = (event) => {
    event.preventDefault()

    setDec(Number(event.target.value));
    setHex(Number(event.target.value).toString(hexagon));
    setEri(Number(event.target.value).toString(hexagon).replaceAll("0","ℓ").replaceAll("1","I").replaceAll("2","V").replaceAll("3","λ").replaceAll("4","＋").replaceAll("5","∀"));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <form onChange={handleSubmit}>
          <label>Decimals: </label>
          <input
            type="number"
            id="decimals"
            name="decimals"
          />
        </form>

        <h1 className={styles.title}>
          Decimal: {dec} = Hexagon: {hex} = Eridian: {eri}
        </h1>

        <iframe type="text/html" sandbox="allow-scripts allow-same-origin allow-popups" width="336" height="550" src="https://read.amazon.co.jp/kp/card?asin=B08FHBV4ZX&preview=inline&linkCode=kpe&ref_=cm_sw_r_kb_dp_2BFE3WC2JM8NZHT0ZK3R" ></iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
